/** Demo profiles and notifications served by the API (same data as former client-side samples). */
export const SAMPLE_PROFILES = [
  {
    id: "1",
    profile_id: "AVS-BR-001",
    type: "bride",
    name: "Priya Selvan",
    age: 25,
    dob: "2001-03-15",
    height: "5'4\"",
    education: "M.E / M.Tech",
    occupation: "IT Professional",
    salary: "8",
    marital_status: "single",
    religion: "Hindu",
    community: "Arunattu Vellalar",
    kothiram: "Kongu Vellalar",
    mother_tongue: "Tamil",
    country: "India",
    state: "Tamil Nadu",
    district: "Coimbatore",
    city: "Coimbatore",
    about:
      "Working as a software engineer in a reputed MNC. Looking for a well-educated partner.",
    family:
      "Father: Retired Government Employee, Mother: Homemaker, 1 Brother (Married)",
    photo_privacy: "public",
    profile_status: "active",
    approval_status: "approved",
    avatar: "PR",
  },
  {
    id: "2",
    profile_id: "AVS-GR-001",
    type: "groom",
    name: "Karthik Raja",
    age: 28,
    dob: "1998-07-22",
    height: "5'10\"",
    education: "MBA",
    occupation: "Business",
    salary: "12",
    marital_status: "single",
    religion: "Hindu",
    community: "Arunattu Vellalar",
    kothiram: "Kongu Vellalar",
    mother_tongue: "Tamil",
    country: "India",
    state: "Tamil Nadu",
    district: "Salem",
    city: "Salem",
    about:
      "Running a family business in textiles. Looking for a caring and understanding life partner.",
    family: "Father: Businessman, Mother: Homemaker, 1 Sister (Married)",
    photo_privacy: "public",
    profile_status: "active",
    approval_status: "approved",
    avatar: "KR",
  },
  {
    id: "3",
    profile_id: "AVS-BR-002",
    type: "bride",
    name: "Divya Kumar",
    age: 24,
    dob: "2002-01-10",
    height: "5'3\"",
    education: "MBBS",
    occupation: "Doctor",
    salary: "10",
    marital_status: "single",
    religion: "Hindu",
    community: "Arunattu Vellalar",
    kothiram: "",
    mother_tongue: "Tamil",
    country: "India",
    state: "Tamil Nadu",
    district: "Madurai",
    city: "Madurai",
    about:
      "Completed MBBS and currently doing internship. Looking for a well-settled groom.",
    family: "Father: Doctor, Mother: Teacher, 1 Brother",
    photo_privacy: "loggedIn",
    profile_status: "active",
    approval_status: "approved",
    avatar: "DK",
  },
  {
    id: "4",
    profile_id: "AVS-GR-002",
    type: "groom",
    name: "Surya Prakash",
    age: 30,
    dob: "1996-11-05",
    height: "5'9\"",
    education: "B.E / B.Tech",
    occupation: "Engineer",
    salary: "15",
    marital_status: "single",
    religion: "Hindu",
    community: "Arunattu Vellalar",
    kothiram: "Kongu Vellalar",
    mother_tongue: "Tamil",
    country: "India",
    state: "Tamil Nadu",
    district: "Chennai",
    city: "Chennai",
    about: "Working in a top IT company. Family oriented and value traditions.",
    family: "Father: Government Employee, Mother: Homemaker, 1 Sister",
    photo_privacy: "public",
    profile_status: "active",
    approval_status: "approved",
    avatar: "SP",
  },
  {
    id: "5",
    profile_id: "AVS-BR-003",
    type: "bride",
    name: "Meena Devi",
    age: 26,
    dob: "2000-05-20",
    height: "5'5\"",
    education: "CA",
    occupation: "CA/Accountant",
    salary: "9",
    marital_status: "single",
    religion: "Hindu",
    community: "Arunattu Vellalar",
    kothiram: "",
    mother_tongue: "Tamil",
    country: "India",
    state: "Tamil Nadu",
    district: "Tiruchirappalli",
    city: "Trichy",
    about:
      "Chartered Accountant working in a Big 4 firm. Loves music and cooking.",
    family: "Father: Bank Manager, Mother: Teacher, No siblings",
    photo_privacy: "public",
    profile_status: "active",
    approval_status: "pending",
    avatar: "MD",
  },
  {
    id: "6",
    profile_id: "AVS-GR-003",
    type: "groom",
    name: "Arun Mohan",
    age: 27,
    dob: "1999-09-12",
    height: "5'11\"",
    education: "M.Sc",
    occupation: "Teacher/Professor",
    salary: "6",
    marital_status: "divorced",
    religion: "Hindu",
    community: "Arunattu Vellalar",
    kothiram: "",
    mother_tongue: "Tamil",
    country: "India",
    state: "Tamil Nadu",
    district: "Thanjavur",
    city: "Thanjavur",
    about:
      "Assistant Professor in a reputed college. Simple and down to earth person.",
    family: "Father: Retired, Mother: Homemaker, 2 Sisters (Married)",
    photo_privacy: "public",
    profile_status: "active",
    approval_status: "approved",
    avatar: "AM",
  },
];

export const SAMPLE_NOTIFICATIONS = [
  {
    id: 1,
    type: "interest",
    message: "Karthik Raja (AVS-GR-001) sent you an interest",
    time: "2 hours ago",
    read: false,
  },
  {
    id: 2,
    type: "match",
    message: "New match found! Surya Prakash matches your preferences",
    time: "1 day ago",
    read: false,
  },
  {
    id: 3,
    type: "approved",
    message: "Your profile has been approved by admin",
    time: "2 days ago",
    read: true,
  },
  {
    id: 4,
    type: "anniversary",
    message:
      "Happy Wedding Anniversary! Wishing you a wonderful year ahead. - AVS Matrimony",
    time: "5 days ago",
    read: true,
  },
];
